
server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Register-System
    username: postgres
    password: 100604
  jpa:
    hibernate:
      ddl-auto: update
upload:
  server:
    folder: D:\upload_file

#jwt:
#  secret: "ThisSecretKey"
#  expirationDate: 5 * 60 * 60 * 1000L
